---
- name: Converge
  hosts: all
  roles:
    - role: ome.docker
      docker_use_ipv4_nic_mtu: true
    - role: ome.redis
    - role: ansible-role-celery-docker
      celery_docker_max_retries: 1
      celery_docker_retry_delay: 1

# Additional tasks for setting up tests
- hosts: all
  tasks:

    - name: Create celery test directory
      become: true
      file:
        path: /tmp/celery
        owner: celery
        state: directory

    - name: Create celery test input
      become: true
      copy:
        dest: /tmp/celery/input.txt
        content: "hello world"
